### ISSUE TITLE
Tracking new packages, recipes and non-FSDS migration

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#1146]
## Description

A number of current ska3-flight packages are used by a well-defined subset of the CXC operations community. In order to facilitate more agile development and deployment of package updates, we propose putting these packages in a new control process which requires review and approval by only the identified stakeholders. This can be done by email.

## Package manifest

| Package | Stakeholders |
| --- | --- |
| aca_hi_bgd | ACA, PCAD |
| aca_weekly_report | ACA |
| acdc | ACA, PCAD |
| aimpoint_mon | ACA, PCAD |
| annie | ACA |
| astromon | ACA, PCAD |
| attitude_error_mon | ACA, PCAD |
| fid_drift_mon | ACA, PCAD |
| fss_check | ACA, PCAD |
| jobwatch | ACA |
| kalman_watch | ACA, PCAD |
| obc_rate_noise_plots | ACA, PCAD |
| perigee_health_plots | ACA, PCAD |
| ska_report_ranges | ACA |
| vv_trending | ACA |
| twiki-wg | ACA |

```[tasklist]
### Tasks
- [ ] https://github.com/sot/skare3/pull/1145
- [ ] https://github.com/sot/twiki-wg/pull/24
- [ ] https://github.com/sot/fid_drift_mon/pull/15
- [ ] https://github.com/sot/fid_drift_mon/pull/16
- [ ] https://github.com/sot/skare3/pull/1138
- [ ] https://github.com/sot/attitude_error_mon/pull/16
- [ ] https://github.com/sot/skare3/pull/1137
- [ ] https://github.com/sot/fss_check/pull/16
- [ ] https://github.com/sot/fss_check/pull/21
- [ ] https://github.com/sot/skare3/pull/1139
- [ ] https://github.com/sot/vv_trending/pull/5
- [ ] https://github.com/sot/skare3/pull/1136
- [ ] https://github.com/sot/skare3/pull/1153
- [ ] https://github.com/sot/attitude_error_mon/pull/18
- [ ] https://github.com/sot/twiki-wg/pull/25
- [ ] https://github.com/sot/obc_rate_noise_plots/issues/4
- [x] Promote ska3 aimpoint_mon
```

```[tasklist]
### Migrated to non-fsds process
- [x] aca_hi_bgd
- [x] aca_weekly_report
- [x] acdc
- [x] aimpoint_mon
- [x] annie
- [x] astromon
- [x] attitude_error_mon
- [x] fid_drift_mon
- [x] fss_check
- [x] jobwatch
- [x] kalman_watch
- [x] perigee_health_plots
- [x] ska_report_ranges
- [x] vv_trending
- [x] twiki-wg
- [x] obc_rate_noise_plots
```
